apiVersion: apps/v1
kind: Deployment
metadata:
  name: shadowtest
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "shadowtest.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "shadowtest.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "shadowtest.labels" . | nindent 8 }}
    spec:
      containers:
        - name: shadowtest
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: Always
          ports:
            - containerPort: {{ .Values.service.port }}
          env:
            - name: PORT
              value: "{{ .Values.service.port }}"
          livenessProbe:
            httpGet:
              path: /health
              port: {{ .Values.service.port }}
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: {{ .Values.service.port }}
            initialDelaySeconds: 10
            periodSeconds: 10
