apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: shadowtest
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      {{- include "shadowtest.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
