apiVersion: v1
kind: Service
metadata:
  name: shadowtest
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "shadowtest.selectorLabels" . | nindent 6 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: http
  selector:
    {{- include "shadowtest.selectorLabels" . | nindent 6 }}
