name: shadowtest
version: '1.1.0'
summary: Web service to test shadowsocks keys
description: Web service to test shadowsocks keys
confinement: strict
base: core20

parts:
  docker-image-save:
    plugin: go
    source: https://github.com/jadolg/ShadowTest
    source-type: git
    build-packages:
      - gcc

apps:
  shadowtest:
    command: bin/ShadowTest
    daemon: simple
    environment:
      PORT: 51292
    plugs:
      - network
      - network-bind
