service:
  port: 8080

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 4
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

image:
  repository: guamulo/shadowtest
  tag: latest

resources:
  limits:
    cpu: 300m
    memory: 512Mi
  requests:
    cpu: 100m
  memory: 256Mi